### ISSUE TITLE
Dead Ai in vehicles , Server thinks they are alive can't get in the ai car

### ISSUE THREAD

**Issue by northrivergeek** [Ghostrider-DbD-/blckeagles-revisited-RC#94] opened 2018-02-13 08:21 UTC
AI are getting stuck in mission vehicles .. they are dead , but for some reason the server thinks they arent .. even after the dead ai inside despawn still can't get in .. had this happen many times this last one was green bandit camp

**Comment by Ghostrider-DbD-** [comment] 2018-02-13 12:07
Do you use a headless client? That seems to make this issue worse. I have it on the list - have not had time to look into the cause. I will try to do so either later this week or next week.

**Comment by northrivergeek** [comment] 2018-02-13 13:05
no not using headless client

**Comment by Ghostrider-DbD-** [comment] 2018-04-24 00:11
I think this may be an arma issues. I am thinking that checking AI damage may be more reliable than testing if any crew of the vehicle are alive.

**Comment by Ghostrider-DbD-** [comment] 2018-04-28 12:27
Dead AI are now ejected from the vehicle which seems to have solved the issue when no HC is connected.
The HC now tracks status of vehicles for AI it owns which addressed issues when it is connected.
Still need to handle transfer of units back to server if HC is disconnected.
Note that vehicles are transferred to server when empty. Also need to track this case to handle cleanup of vehicles that are not entered by players before the timeout occurs.

**Comment by Ghostrider-DbD-** [comment] 2018-08-05 11:29
Identified the cause of the issues when an HC is connected, which is that setVehicleLock is local to the machine it was executed on. I will have to either execute the releaseVehicleToPlayers function on the HC, or execute setVehicleLock.

**Comment by Ghostrider-DbD-** [comment] 2018-08-05 11:53
In addition, action "Eject" is also local so needs to be called on the HC with remoteExec.

**Comment by Ghostrider-DbD-** [comment] 2018-08-05 20:48
Should be resolve with Build 149.

**Comment by Ghostrider-DbD-** [comment] 2018-12-01 06:03
Resolved with build 167.

**Closed by Ghostrider-DbD-** 2018-12-01 06:03 UTC
Labels: bug
